title: Bot Framework Solutions
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for Bot Framework Solutions projects including 
  Virtual Assistant and Skills.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_repo: https://github.com/microsoft/botframework-solutions

# custom properties
show_full_navigation: true

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "_docs/tutorials"
    values:
      layout: tutorial
  - scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  